// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjCN53kuKr7Zu-ZKt_8S9Ne_Wk-7zgW9U',
    appId: '1:526440664513:web:79db98cbeb5990d64eb340',
    messagingSenderId: '526440664513',
    projectId: 'my-notificatins-app',
    authDomain: 'my-notificatins-app.firebaseapp.com',
    storageBucket: 'my-notificatins-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQsXdSCjLMEnYswcI5D2SMptuzpoXCfbo',
    appId: '1:526440664513:android:f70d8e5a6bbe8d7b4eb340',
    messagingSenderId: '526440664513',
    projectId: 'my-notificatins-app',
    storageBucket: 'my-notificatins-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOGwrI1tV32LdzUbHkJ0_U63h7Pcca544',
    appId: '1:526440664513:ios:99197081cac453a54eb340',
    messagingSenderId: '526440664513',
    projectId: 'my-notificatins-app',
    storageBucket: 'my-notificatins-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOGwrI1tV32LdzUbHkJ0_U63h7Pcca544',
    appId: '1:526440664513:ios:99197081cac453a54eb340',
    messagingSenderId: '526440664513',
    projectId: 'my-notificatins-app',
    storageBucket: 'my-notificatins-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjCN53kuKr7Zu-ZKt_8S9Ne_Wk-7zgW9U',
    appId: '1:526440664513:web:5773369e96aaf0dc4eb340',
    messagingSenderId: '526440664513',
    projectId: 'my-notificatins-app',
    authDomain: 'my-notificatins-app.firebaseapp.com',
    storageBucket: 'my-notificatins-app.firebasestorage.app',
  );
}
